name: Deploy Lambda Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  terraform:
    name: Terraform Verification and Push Lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0
          terraform_wrapper: false

      - name: Initialize Terraform for Lambda
        working-directory: deploy/terraform
        run: terraform init

      - name: Validate Terraform for Lambda
        working-directory: deploy/terraform
        run: terraform validate

      - name: Plan Terraform for Lambda
        if: github.ref == 'refs/heads/main' # Executa apenas na branch main
        working-directory: deploy/terraform
        run: terraform plan -out=lambda

      - name: Apply Terraform for Lambda
        if: github.ref == 'refs/heads/main' # Executa apenas na branch main
        working-directory: deploy/terraform
        run: terraform apply -auto-approve lambda


  build-image-and-push:
    name: Build Docker Image and Push to ECR, Update Lambda
    runs-on: ubuntu-latest

    env:
      AWS_LAMBDA_FUNCTION_NAME: ${{ vars.AWS_LAMBDA_FUNCTION_NAME }}
      AWS_ECR_REPOSITORY_URL: ${{ vars.AWS_ECR_REPOSITORY_URL }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ vars.AWS_ECR_AUTH_ENDPOINT }}

      - name: Build Docker image
        run: |
          docker build -t $AWS_ECR_REPOSITORY_URL:latest .

      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ECR_REPOSITORY_URL:latest

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name $AWS_LAMBDA_FUNCTION_NAME \
            --image-uri $AWS_ECR_REPOSITORY_URL:latest
